### ISSUE TITLE
dream.lua issue : '}' expected to close '{' at line 19 near '='

### ISSUE THREAD

**Issue by Smethan** [Xavyrr/LOVE#1]
When I compile the game, it gives an error that is something like the title when I run it, and after looking at the code, it seems all the closing brackets are there, so I don't know why this issue is appearing and I would like to know so I could continue development. Would it be a problem with LOVEPotion being updated, or is the code just a mess?

**Comment by sadkris** [comment]
Getting the same Issue. If you look closer at the parenthesis it includes the parenthesis in the error

**Comment by Smethan** [comment]
Sort of as an addition, what is the "w =" bit at the end of line 20 in dream.lua? What is w?

**Comment by sadkris** [comment]
I noticed that too... deleting it changes the error

**Comment by Smethan** [comment]
Okay, I solved the error by getting an older working version and working from there instead. You can check out my fork for all that stuff

**Comment by sadkris** [comment]
I just installed the QR version

**Comment by sadkris** [comment]
Works perfectly when DSP is dumped. Its damn small tho

**Comment by Smethan** [comment]
Yeah, I'm working on expanding it. I've gotta rewrite the collision code before I add a new room though, since the current code won't work for rooms with more than 4 walls. After that I might work on making the battle system.
